# This is a basic workflow to help you get started with Actions

name: SwaggerPetStoreAPICollection

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Create dir
        run: | 
          mkdir HtmlReport

      # Install Node.js
      - name: Install Node
      - uses: actions/checkout@v4
      - with: 
          node-version: '17.x'

      # Insatall Newman and Reporter
      - name: Install Newman
        run: |
           npm install -g newman
           npm install -g newman-reporter-htmlextra
      # Run Collection
      - name: Run Collection
        run: | 
           newman run "01 - Swagger Petstore.postman_collection.json" 
	 
      # Publish the Report
      - name: publish report
      - uses: actions/checkout@v4
        with: 
           name: Reports
           path: HtmlReport
      
      

          

     
